### ISSUE TITLE
hub.db.password doesn't work on 0.11.1

### ISSUE THREAD

**Issue by duongnt** [jupyterhub/zero-to-jupyterhub-k8s#2120] opened 2021-03-30 05:26 UTC
### Bug description

hub.db.password doesn't work on 0.11.1, which is the latest stable release I could find. 

hub.db.password is set in the secret, however it's not picked up in jupyterhub_config.py (this looks like fixed in master, but it hasn't been released yet).

#### Expected behaviour

hub.db.password to work on a stable release. 

### Your personal set up

 - OS:
 
 - Version(s):
 

- <details><summary>Full environment</summary>

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
# jupyterhub_config.py
```
</details>

- <details><summary>Logs</summary>

```
# paste relevant logs here, if any
```
</details>

**Comment by consideRatio** [comment] 2021-03-30 07:11
When you say "is set in the secret"?, do you mean your configuration or something else?

**Comment by consideRatio** [comment] 2021-04-09 15:58
I'll go ahead and close this issue, please provide more information if you think it is still an unfixed issue in master that we need to track and address.

**Closed by consideRatio** 2021-04-09 15:58 UTC
Labels: bug

**Comment by andrewm-aero** [comment] 2021-07-30 15:43
(Sorry for raising a dead issue, let me know if you'd prefer I make a fresh one)

I'm not certain if this is the same issue, but I encountered a similar issue with 1.1.1 yesterday. Here's how to reproduce:

1. Install a separate postgres DB (We use https://github.com/zalando/postgres-operator)
2. Set `hub.db.url` (sans password) to external postgres, `hub.db.upgrade` to `true`, and `hub.existingSecret` to an arbitrary secret name, in the helm chart values
3. Set `hub.db.password` in the `values.yaml` key in the secret pointed to by `hub.existingSecret`.
4. Install fresh helm chart, making sure that the DB is blank (no schema).
5. Observe that schema upgrade fails, stating `fe_sendauth: no password supplied` in hub deployment pod logs.

Workaround: Set `hub.db.url` in the manually managed secret (with password this time), and don't set `hub.db.password` in that secret.

While its still possible to use an external DB, its not ideal, as we use gitops via ArgoCD to manage our helm releases, and we'd prefer to have everything non-sensitive in git, and have the absolute minimum in manually-managed secrets.

**Comment by consideRatio** [comment] 2021-07-30 18:33
hub.existingSecret reworked significantly since 0.11.1, i assume it is not relevant. If you can reproduce the issue in version 1.1.1 do open a new issue, but i think this is resolved.

**Comment by consideRatio** [comment] 2021-07-30 20:25
Btw read the latest docs on hub.existingSecret in the config reference on z2jh.jupyter.org, i recall there was a disclaimer i wrote about this.
