### ISSUE TITLE
proxy.https setting fails: PEM_read_bio:no start line

### ISSUE THREAD

**Issue by anton-khodak** [jupyterhub/zero-to-jupyterhub-k8s#940] opened 2018-09-17 15:35 UTC
Hi,

I have a problem in working out https on the JupyterHub installation. For the config file below, I get the following error from `proxy`:

```
$ kubectl logs proxy-bb7cb7d7-k7xrn
08:48:28.459 - info: [ConfigProxy] Adding route / -> http://10.233.50.98:8081
_tls_common.js:85
      c.context.setKey(options.key, options.passphrase);
                ^

Error: error:0906D06C:PEM routines:PEM_read_bio:no start line
    at Error (native)
    at Object.createSecureContext (_tls_common.js:85:17)
    at Server (_tls_wrap.js:776:25)
    at new Server (https.js:26:14)
    at Object.exports.createServer (https.js:47:10)
    at new ConfigurableProxy (/usr/local/lib/node_modules/configurable-http-proxy/lib/configproxy.js:219:32)
    at Object.<anonymous> (/usr/local/lib/node_modules/configurable-http-proxy/bin/configurable-http-proxy:226:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```
Without `proxy.https` section everything works fine.

Googling didn't help much with 
```
error:0906D06C:PEM routines:PEM_read_bio:no start line
```
The certificate is valid, it's a wildcard certificate with a chain from Let's encrypt. There is a comparable issue in JupyterHub repo: https://github.com/jupyterhub/jupyterhub/issues/570, but my certificate is already concatenated. 

## Contents of `config.yaml` (some fields omitted for brevity)
```
proxy:
    secretToken: <token>
    https:
      hosts:
        - jupyter.cellgeni.sanger.ac.uk
        - jupyter-proxy.cellgeni.sanger.ac.uk
      type: manual
      manual:
        key:  |
          ----BEGIN PRIVATE KEY-----
          <key>
          -----END PRIVATE KEY-----
        cert:  |
          -----BEGIN CERTIFICATE-----
         <cert>
          -----END CERTIFICATE-----	
          -----BEGIN CERTIFICATE-----
         <cert>
          -----END CERTIFICATE-----

singleuser:
  image:
    name: quay.io/cellgeni/cellgeni-jupyter
    tag: v0.2.4
```

**Comment by frafi82** [comment] 2019-02-06 16:08
Did you find the cause/problem ??

**Comment by anton-khodak** [comment] 2019-02-07 10:12
@frafi82 no, unfortunately, had to use a reverse proxy for https

**Comment by doutriaux1** [comment] 2019-04-29 22:06
@anton-khodak I'm hitting what seems to be the same error, how did you get around it?

**Comment by anton-khodak** [comment] 2019-04-30 08:30
@doutriaux1 see my reply above

**Comment by consideRatio** [comment] 2020-10-05 22:42
I'm not sure what to do about this, or why, but I would suggest debugging this by trying to figure out if you get the certificates mounted to the pod correctly. To do so, you could `kubectl edit deploy/proxy` and change the command to `sleep infinity` or similarly to get some time before it crashes, and then you can `kubectl exec -it deploy/proxy -- ls <mount-path-here>`, and you know the mount path by using `kubectl describe deploy/proxy` ahead of time.

Please feel free to open a new issue if you fail to get manually provided certs to function as it should with this Helm chart, for now I'm closing as this was reported 2 years ago and I'm not sure if its fixed or not and have ~300 issues in repo.

**Closed by consideRatio** 2020-10-05 22:42 UTC
