### ISSUE TITLE
A secrets friendly version of extraEnv

### ISSUE THREAD

**Issue by xrl** [jupyterhub/zero-to-jupyterhub-k8s#1103] opened 2019-01-14 04:29 UTC
I am looking for design feedback on a more general version of `extraEnv`. I have looked over #440 and it makes valid points but doesn't talk about a design to move forward.

Folks are going to be creating multi-user jupyter hubs where they'll want all environment to share some base secrets. I'm thinking AWS IAM credentials for reading from buckets or athena. We're not talking about "admin for everything" kind of credentials.

While these secrets are low impact I would rather not keep them in my `values.yml` used for the jhub release. What if I wanted to keep my kube config project as an open repo? I should be able to balance transparent kube objects and kube's secret system. Also, I want all my secrets in kubernetes so I can more easily audit and roll them later.

Could we convert `extraEnv` back to a more "raw" format? Instead of the current `envKey: envValue` key-pair, could we do a list of native kubernetes env values? We would absolutely be giving up the convenience in exchange for a more verbose but ultimately far more powerful format. A blind substition is also more the style of helm charts.

So `envFrom` would be something like:

```
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      value: 1234ABCD
```

and if they wanted to mount a secret instead:

```
  extraEnv:
    - name: AWS_ACCESS_KEY_ID
      valueFrom:
        secretKeyRef:
          name: jupyter-user
          key: AWS_ACCESS_KEY_ID
```

Perhaps we don't want to break folks values.yml, what would be another good `values.yml` key to use?

**Comment by minrk** [comment] 2019-01-15 10:08
> could we do a list of native kubernetes env values?

I definitely think we should move toward standard kube structures as much as possible. However, we've also learned that list config doesn't work well for hierarchical charts since they don't get merged (setting extraEnv in one chart that includes jupyterhub means deployments must be aware of and duplicate all of the extraEnv in that chart in their deployment if they want to set any env without clobbering). Dicts merge a lot nicer, so I'm somewhat inclined to deviate from the spec only in that the config ought to be a dict somehow. There are two ways I see to do that:

1. a dict of exactly kubernetes [EnvVar](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.13/#envvar-v1-core) arrays that just get concatenated, or
2. a dict keyed by env name where the body is *either* a simple env value (current), or an EnvVar struct.

We already do pattern number 1 where we've encountered this hierarchy before, in extraConfig. It's useful, but has also proven confusing to users who often omit the extra layer of keys, which doesn't make a lot of sense when writing your own config, since the key is arbitrary and any given deployment likely only has the one. Pattern 2 is the smallest deviation from the current spec, but is also a bit more custom and requires more logic (type checking) in the chart. I'm not sure which is best from a user perspective.

**Comment by MrSaints** [comment] 2019-05-16 16:13
I'd be quite keen on injecting secrets as environment variables to user pods as well. As a workaround, there is https://kubernetes.io/docs/tasks/inject-data-application/podpreset/, but it is not available in most managed solutions.

**Comment by sgloutnikov** [comment] 2019-10-24 23:17
Also ran into the need to mount secrets as environment variables into the user pod and ended up with two options. For now, the first one looks easier to manage as there are less moving pieces. 

1) Use `hub.extraConfig` to alter `c.KubeSpawner.modify_pod_hook`. The idea came from the following kubespawner [issue](https://github.com/jupyterhub/kubespawner/issues/306). You would do something like this in your `values.yaml` file to append as many ENV variables as needed:

```yaml
hub:
  extraConfig:
    ...
    10-secretToEnv: |
      from kubernetes import client
      def modify_pod_hook(spawner, pod):
          pod.spec.containers[0].env.append(
              client.V1EnvVar(
                  name='YOUR_ENV_VARIABLE', 
                  value_from=client.V1EnvVarSource(
                      secret_key_ref=client.V1SecretKeySelector(
                          name='your-secret',
                          key='SECRET_KEY',
                      )
                  )
              )
          )
          return pod
      c.KubeSpawner.modify_pod_hook = modify_pod_hook
    ...
```

2. Mount the secret(s) to the `singleuser.storage` filesystem and add a `singleuser.lifecycleHooks.podStart.exec.command` (some bash script) to read over the appropriate files and create a `.bash_profile` with the ENV variables and values. You now have the secrets mounted as ENV variables in the login shell, but launching a new kernel will not source them, as discussed in the following JupyterHub [issue](https://github.com/jupyterhub/jupyterhub/issues/330). Add a simple `kernel-helper.sh` script to be executed as the first `argv` argument in your kernel(s) `kernel.json`. This will start the kernel in the same environment as the login shell. 

kernel-helper.sh:
```bash
#!/bin/bash -il
exec "$@"
```

```yaml
singleuser:
  storage:
    extraVolumes:
      - name: mysecrets
        secret:
          secretName: your-secret
    extraVolumeMounts:
      - name: mysecrets
        mountPath: /etc/secrets
```

**Comment by jtlz2** [comment] 2019-11-19 14:10
@sgloutnikov Did (1) work? :\

**Comment by sgloutnikov** [comment] 2019-12-02 06:44
@jtlz2 yes, both worked. Not in the example above, but I went with a loop in there to minimize on copy-pasting a bunch of the same code since ENV variable and key were the same name.

**Comment by chrisroat** [comment] 2020-05-22 00:45
Is there a specific proposal here?  I believe this is a very nice idea.

**Closed** 2020-09-04 06:55 UTC

**Comment by consideRatio** [comment] 2020-09-04 07:32
This should now be supported, as documented in the configuration reference both for [hub.extraEnv](https://zero-to-jupyterhub.readthedocs.io/en/latest/reference/reference.html#hub-extraenv) and [singleuser.extraEnv](https://zero-to-jupyterhub.readthedocs.io/en/latest/reference/reference.html#singleuser-extraenv).

Thanks for reporting and thumbing up interacting etc, it was very useful to see 17 thumbs up on the issue to help prioritize this issue!

**Comment by peterrmah** [comment] 2020-09-09 18:17
@consideRatio I can confirm the extraEnv worked successfully on my deployment. Thanks for the help!

**Comment by MattiasVahlberg** [comment] 2020-09-21 14:03
@peterrmah What version of helm chart did you use when you got this to work? I've tried with 0.9.0 but did not get it to work.. 
Reference to secrets:
`    ENV_VAR:
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: secret1`

But getting errors when trying to spawn a new pod.

**Comment by consideRatio** [comment] 2020-09-21 14:11
@MattiasVahlberg try `0.9.0-n251.h9594ed30` for example, its the latest as seen from pressing the orange badge in the repo's README.md and pressing "development releases" on the site you arrive to.

**Comment by peterrmah** [comment] 2020-09-21 22:03
@MattiasVahlberg I was using version 0.9.0

**Comment by consideRatio** [comment] 2020-09-21 22:55
@peterrmah hmmm, support for this syntax was introduced after `0.9.0`, in `0.9.0-nXXX.hXXXXXXX` something.

```
ENV_VAR:
  valueFrom:
    secretKeyRef:
      name: mysecret
      key: secret1
```

**Comment by metasim** [comment] 2020-09-24 15:45
I'm also not able to get this to work in the `hub` section, version 0.9.1. The secret gets expanded like this.

```
name: "CLIENT_SECRET"
value: "map[name:CLIENT_SECRET valueFrom:map[secretKeyRef:map[key:CLIENT_SECRET name:app-secrets]]]"
```

**Comment by consideRatio** [comment] 2020-09-24 15:49
@metasim sorry, the 0.9.1 is confusingly older than the latest development version prefixed `0.9.0`.

This is of course unwanted and cause confusion. The technical mumbo-jumbo relates to 0.9.1 was a single-commit security patch to 0.9.0 while 0.9.0-nXXX.hXXXXXXX are all the commits since 0.9.0, which also includes the single commit patch released as 0.9.1.

**Comment by kyprifog** [comment] 2020-11-06 17:31
@consideRatio Is there a verison of 0.9.1 where this works?  I had downgraded to the version you had stated, but it breaks with other components i'm using (namely dask-gateway) which seems to only work with `0.9.1` and up on my testing.

**Comment by kamac** [comment] 2020-11-09 12:37
@kyprifog Can you upgrade to `0.10.2`? I believe that's the newest version, and it works for me there.

**Comment by kyprifog** [comment] 2020-11-09 15:19
Hmm, upgraded to 0.10.2 but I'm stilling getting 
```
        - name: SECRET
          value: >-
            map[valueFrom:map[secretKeyRef:map[key:SECRET
```
in the manifest

**Comment by kyprifog** [comment] 2020-11-10 14:01
Thanks, @kamac I confirmed that upgrading to 0.10.2 did indeed fix the problem.  Now I have to deal with the fact that upgrade broke daskhub for me, but thats a different issue (specifically this one:  https://github.com/dask/helm-chart/issues/130 )

**Comment by consideRatio** [comment] 2020-11-10 15:43
> Thanks, @kamac I confirmed that upgrading to 0.10.2 did indeed fix the problem. Now I have to deal with the fact that upgrade broke daskhub for me, but thats a different issue (specifically this one: dask/helm-chart#130 ) :)

@kyprifog if something broke when upgrading to 0.10.2, I guess it relates to networkpolicy enforcement. Did some pod try to access the hub pod directly without a `hub.jupyter.org/network-access-hub: "true"` label in the same namespace for example?

You could conclude if its about netwrok policies by disabling them for the. See the z2jh configuration reference about that.

**Comment by kyprifog** [comment] 2020-11-10 19:03
@consideRatio, apologies, I didn't actually mean to continue the conversation beyond that comment but thanks for the reply!  I'll pursue any follow ups in the linked issue.
