### ISSUE TITLE
Active Directory LDAP Authentication

### ISSUE THREAD

**Issue by narion** [jupyterhub/zero-to-jupyterhub-k8s#1166] opened 2019-02-27 14:57 UTC
To resolve an issue with the active directory allowedGroups configuration item the line spacing in the documentation is incorrect. 

Documentation shows allowedGroups inline with the dn: setting however this does not then actually manage the checking of user groups. I had to indent the allowedGroups item to match the items listed within user: (a further 4 spaces in the yml/yaml)

Being specific in the code displayed guide page is `https://z2jh.jupyter.org/en/latest/authentication.html:- 

```yaml
auth:  
  type: ldap  
  ldap:  
    server:  
      address: ad.EXAMPLE.org  
    dn:  
      lookup: true  
      search:  
        filter: '({login_attr}={login})'  
        user: 'ldap_search_user_technical_account'  
        password: 'secret'  
      templates:  
        - 'uid={username},ou=people,dc=wikimedia,dc=org'  
        - 'uid={username},ou=developers,dc=wikimedia,dc=org'  
      user:  
        searchBase: 'ou=people,dc=wikimedia,dc=org'  
        escape: False  
        attribute: 'sAMAccountName'  
        dnAttribute: 'cn'  
    allowedGroups:
      - 'cn=researcher,ou=groups,dc=wikimedia,dc=org'  
      - 'cn=operations,ou=groups,dc=wikimedia,dc=org'
```	  
To get the allowedGroups working I had to format as follows:- 
```yaml
auth:  
  type: ldap  
  ldap:  
    server:  
      address: ad.EXAMPLE.org  
    dn:  
      lookup: true  
      search:  
        filter: '({login_attr}={login})'  
        user: 'ldap_search_user_technical_account'  
        password: 'secret'  
      templates:  
        - 'uid={username},ou=people,dc=wikimedia,dc=org'  
        - 'uid={username},ou=developers,dc=wikimedia,dc=org'  
      user:  
        searchBase: 'ou=people,dc=wikimedia,dc=org'  
        escape: False  
        attribute: 'sAMAccountName'  
        dnAttribute: 'cn'  
        allowedGroups:
          - 'cn=researcher,ou=groups,dc=wikimedia,dc=org'  
          - 'cn=operations,ou=groups,dc=wikimedia,dc=org'
```

**Comment by hqwl159** [comment] 2020-07-21 07:46
yeal! I hava the same issue.  
I don't know what's  the mean of  config "ldap.dn.search.user". It's don't work either  'ldap.dn.search.user = ldap_search_user_technical_account' or   'ldap.dn.search.user = ${my ldap admin user}'

This is my config:
`auth:
  admin:
    access: true
    users:
      - xxxxx
  type: ldap
  ldap:
    server:
      address: 10.1.21.30
      port: 10389
    dn:
      lookup: true
      search:
        filter: '({login_attr}={login})'
        user: '*****'
        password: '******'
      templates:
        - 'uid={username},ou=people,dc=hduldap,dc=com'
        - 'uid={username},ou=developers,dc=hduldap,dc=com'
      user:
        searchBase: 'ou=people,dc=hduldap,dc=com'
        escape: False
        attribute: 'sAMAccountName'
        dnAttribute: 'cn'
    allowedGroups:
      - 'cn=researcher,ou=groups,dc=hduldap,dc=com'
      - 'cn=operations,ou=groups,dc=hduldap,dc=com'
  state:
    enabled: true
   cryptoKey: "cabaf09e100a9483c737e1af998fff927373ee929815e126f28ee9ff6f320897"
`

**Comment by narion** [comment] 2020-07-21 07:54
> Yeal! I hava the same issue.
> I don't know what's the mean of config "ldap.dn.search.user". It's don't work either 'ldap.dn.search.user = ldap_search_user_technical_account' or 'ldap.dn.search.user = ${my ldap admin user}'
> 
> my juputerhub/k8s version is 0.9.0
> 
> This is my config:
> 
> ```
> auth:
>   admin:
>     access: true
>     users:
>       - xxxxx
>   type: ldap
>   ldap:
>     server:
>       address: 10.1.21.30
>       port: 10389
>     dn:
>       lookup: true
>       search:
>         filter: '({login_attr}={login})'
>         user: '*****'
>         password: '******'
>       templates:
>         - 'uid={username},ou=people,dc=hduldap,dc=com'
>         - 'uid={username},ou=developers,dc=hduldap,dc=com'
>       user:
>         searchBase: 'ou=people,dc=hduldap,dc=com'
>         escape: False
>         attribute: 'sAMAccountName'
>         dnAttribute: 'cn'
>     allowedGroups:
>       - 'cn=researcher,ou=groups,dc=hduldap,dc=com'
>       - 'cn=operations,ou=groups,dc=hduldap,dc=com'
>   state:
>     enabled: true
>    cryptoKey: "cabaf09e100a9483c737e1af998fff927373ee929815e126f28ee9ff6f320897"
> ```

 user:
         searchBase: 'ou=people,dc=hduldap,dc=com'
         escape: False
         attribute: 'sAMAccountName'
         dnAttribute: 'cn'
         allowedGroups:
           - 'cn=researcher,ou=groups,dc=hduldap,dc=com'
           - 'cn=operations,ou=groups,dc=hduldap,dc=com'

:)

**Comment by hqwl159** [comment] 2020-07-21 09:46
> > Yeal! I hava the same issue.
> > I don't know what's the mean of config "ldap.dn.search.user". It's don't work either 'ldap.dn.search.user = ldap_search_user_technical_account' or 'ldap.dn.search.user = ${my ldap admin user}'
> > my juputerhub/k8s version is 0.9.0
> > This is my config:
> > ```
> > auth:
> >   admin:
> >     access: true
> >     users:
> >       - xxxxx
> >   type: ldap
> >   ldap:
> >     server:
> >       address: 10.1.21.30
> >       port: 10389
> >     dn:
> >       lookup: true
> >       search:
> >         filter: '({login_attr}={login})'
> >         user: '*****'
> >         password: '******'
> >       templates:
> >         - 'uid={username},ou=people,dc=hduldap,dc=com'
> >         - 'uid={username},ou=developers,dc=hduldap,dc=com'
> >       user:
> >         searchBase: 'ou=people,dc=hduldap,dc=com'
> >         escape: False
> >         attribute: 'sAMAccountName'
> >         dnAttribute: 'cn'
> >     allowedGroups:
> >       - 'cn=researcher,ou=groups,dc=hduldap,dc=com'
> >       - 'cn=operations,ou=groups,dc=hduldap,dc=com'
> >   state:
> >     enabled: true
> >    cryptoKey: "cabaf09e100a9483c737e1af998fff927373ee929815e126f28ee9ff6f320897"
> > ```
> 
> The indentation on the allowedGroups needs to be within user, the documentation really needs updating as I'd completely forgotten I'd ever posted this...

Thank you for your reply!!! I alter the config:
```
auth:
  admin:
    access: true
    users:
      - hqwl159
  type: ldap
  ldap:
    server:
      address: 10.1.21.30
      port: 10389
    dn:
      lookup: true
      search:
        filter: '({login_attr}={login})'
        user: 'ldap_search_user_technical_account'
        password: 'secret'
      templates:
        - 'uid={username},ou=people,dc=hduldap,dc=com'
        - 'uid={username},ou=developers,dc=hduldap,dc=com'
      user:
        searchBase: 'ou=people,dc=hduldap,dc=com'
        escape: False
        attribute: 'sAMAccountName'
        dnAttribute: 'cn'
        allowedGroups:
          - 'cn=researcher,ou=groups,dc=hduldap,dc=com'
          - 'cn=operations,ou=groups,dc=hduldap,dc=com'
```

But it don't work with “500 : Internal Server Error”.
It can work with auth by github.
Do you have right configuration file about auth of  juputerhub  with ldap?Could  you shared your configuration file with me ？

**Comment by narion** [comment] 2020-07-21 09:51
Sadly no sorry, we no longer have that setup active in our environment at present. But including the allowedGroups value into user worked for us.

**Comment by hqwl159** [comment] 2020-07-21 10:30
> Sadly no sorry, we no longer have that setup active in our environment at present. But including the allowedGroups value into user worked for us.

It doesn't matter. Thank you for your attention.

**Comment by manics** [comment] 2020-07-21 10:34
Hi all. It looks like there's some useful information in here. Due to the complexity and difficulty in testing I think this would be a nice addition to the [Jupyter community forum](https://discourse.jupyter.org/) as a wiki post. Is anyone interested in writing it?

**Comment by consideRatio** [comment] 2020-10-06 02:26
- From [this code inspection](https://github.com/jupyterhub/ldapauthenticator/blob/b32a5ea23449edc0519ba4cd86dd0cc0c36896d5/ldapauthenticator/ldapauthenticator.py#L72), it seems from the configuration, that allowed_groups should not be under user:, but directly under ldap:
- From [this code inspection](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/a2c3ef80932d4ae45cde562823c76155ccfc8897/jupyterhub/files/hub/jupyterhub_config.py#L347) where we consume the values it seems correct as well.

I'm really confused if it would work as intended with indented configuration, I believe indented configuration rather made the allowedGroups be ignored by ldapauthenticator, and that made things work by allowing all instead or similarly.

I'm closing this issue as I cannot translate it to a clear action point for this repo =/

**Closed by consideRatio** 2020-10-06 02:26 UTC
