### ISSUE TITLE
hub not accessible when switching from helm 0.8.2 to 0.9.0-beta.4

### ISSUE THREAD

**Issue by adi413** [jupyterhub/zero-to-jupyterhub-k8s#1594] opened 2020-03-06 15:25 UTC
**Issue I am facing**
I am trying to switch from helm stable version 0.8.2 of jupyterhub to beta version 0.9.0-beta.4 so that I can use the named server functionality. When I trying to do that https is not working and if I find the public-proxy ip address I am not able to access hub on https.

**Description**

If I try to directly upgrade the helm release with a different version number then I get the following ***error: kind ConfigMap with the name "traefik-proxy-config" already exists in the cluster and wasn't defined in the previous release. Before upgrading, please either delete the resource from the cluster or remove it from the chart***

To shift from version 0.8.2 to 0.9.0-beta.4 I need to first delete the release with version 0.8.2 and then install hub with version 0.9.0-beta.4. This deploys the changes with https enabled then I cannot access the public proxy ip address generated by hub.
I need to disable auto-https and then I can access hub.

It will be great if you can tell me why this might be happening and what can be done to fix this

**Comment by consideRatio** [comment] 2020-03-06 16:15
I'm not sure what has led to this, but I would recommend deleting the k8s configmap called `traefik-proxy-config` manually, then activate https in `0.9.0-beta.4`. To delete the configmap you would do something like `kubectl delete configmap -n jupyterhub traefik-proxy-config`.

Helm can make us end up in some weird states if upgrades are aborted halfway through or fail mid way sometimes, and that is what has happened here I think. So, I don't think this is an issue of the helm chart itself necessarily, so I don't we can ensure this never happens again for anyone sadly. I've had similar failures before with other resources.

**Comment by consideRatio** [comment] 2020-03-06 16:17
Oh btw, to avoid bugs related to helm, ensure to avoid Helm v2.15.X, it had some bugs that I remember reading causing issues, so ensure you use Helm 2.16.X both locally (`helm`) and in your k8s cluster (`tiller`), as reported by `helm --version`.

You can upgrade by writing `helm init --upgrade --service-account tiller` if I recall correctly, after you have made sure your local helm version is up to date.

**Comment by adi413** [comment] 2020-03-06 16:55
I tried it, it is still not working when I enable https.
this is proxy settings to enable in config.yaml file (I am using GKE)
proxy:
  secretToken: "random hash"
  https:
    enabled: true
    hosts:
      - some url
    letsencrypt:
      contactEmail: my email

**Comment by adi413** [comment] 2020-03-06 20:24
Update, I was looking into the logs and getting this message `Unable to obtain ACME certificate for domains \"xxxxxxxxx\" : cannot get ACME client get directory at 'https://acme-v02.api.letsencrypt.org/directory': Get https://acme-v02.api.letsencrypt.org/directory: net/http: TLS handshake timeout" providerName=le.acme`

**Comment by consideRatio** [comment] 2020-03-06 21:38
Do you have a public IP to reach the proxy-public service through, and does your domain point to this IP?

The "error copying from remote stream" etc is something I've gotten a lot here and there, but that seems like an error that doesn't cause any harm, so that we can ignore I think. It does not relate to this helm chart installation at least I think.

**Comment by adi413** [comment] 2020-03-06 21:40
Yes, I have public IP, and if i downgrade and use 0.8.2 it works perfectly fine but as soon as I go to 0.9.0.xx it stops working with ssl and I start getting ssl error

**Comment by consideRatio** [comment] 2020-03-06 21:42
Try deleting your k8s secret with the old certificate, I remember Letsencrypt wrote about a bug affecting 2% or so of the users, you may be one. If you delete the current secret and restart the hub etc, it is meant to recreate it anyhow so try that.

**Comment by consideRatio** [comment] 2020-03-06 21:43
Hmmm, I don't remember what the secret will be named, don't delete `hub-secret`, but some other of a tls kind.

**Comment by consideRatio** [comment] 2020-03-06 21:44
```
kubectl get secrets -n jupyterhub
```

**Comment by adi413** [comment] 2020-03-06 21:45
<img width="644" alt="Screen Shot 2020-03-06 at 4 44 59 PM" src="https://user-images.githubusercontent.com/49159227/76124994-ded83d00-5fc9-11ea-9a19-1905d0320d6d.png">
I see this right now.

**Comment by adi413** [comment] 2020-03-06 21:54
I tried deleting the tls-scme secret, it still it getting same ERR_SSL_PROTOCOL_ERROR, For some reason the ssl handshake is not going through.
Do I need to setup ingress too, with version 0.8.2 just setting proxy and enabling HTTPS as per documentation. works perfectly fine.

**Comment by adi413** [comment] 2020-03-09 14:24
@consideRatio Is there any way I can access and see named servers with version 0.8.2. I know the UI only comes in JHUB version 1.x but is there any way I can manually do it by adding some custom code or using latest hub with helm.

**Comment by snickell** [comment] 2020-03-11 02:52
Just found this issue after already posting to Discourse (https://discourse.jupyter.org/t/trouble-getting-https-letsencrypt-working-with-0-9-0-beta-4/3583/2), I believe I'm experiencing the same issue moving from 0.8.x to 0.9.0-beta4. 

I'm going to try deploying my config to a fresh cluster to see if this is a migration issue, or also is a problem in a fresh install.

**Comment by snickell** [comment] 2020-03-11 02:56
Worth noting that my experience parallels @adi413 . I first ran into the "error: kind ConfigMap with the name "traefik-proxy-config" already exists" type errors, ended up deleting pretty much every configmap in the cluster, did a complete `helm delete --purge ____` on the deploy, and started with an "(almost?) from scratch cluster". After this, the deploy succeeded, BUT I can't access the server with https wrong, and I'm getting the same errors on the autohttps pod as @adi413 .

**Comment by snickell** [comment] 2020-03-11 03:14
@adi413 Are you deploying on a local k8s cluster, aws, gcloud, etc?

**Comment by adi413** [comment] 2020-03-11 13:13
@snickell you will have to do a helm delete --purge <release-name> and they deploy again

do a helm search. jupyterhub and there is a new 0.9xxx version visible now, which was recently deployed. If you use that then your https and everything will work perfectly

**Comment by snickell** [comment] 2020-03-13 01:03
> @snickell you will have to do a helm delete --purge and they deploy again
> 
> do a helm search. jupyterhub and there is a new 0.9xxx version visible now, which was recently deployed. If you use that then your https and everything will work perfectly

Just to confirm for future people: I had already done a `helm delete --purge` before beploying 0.9.0-beta.4. Also, I get the same problem with 0.9.0-beta.4 on a fresh cluster.

HOWEVER, I do *not* get this problem with the newer `0.9.0-beta.4.n008.hb20ad22` that I think @adi413 is referring to. So if you experience this problem with beta.4, try `0.9.0-beta.4.n008.hb20ad22`.

**Comment by snickell** [comment] 2020-03-13 01:06
Unless @adi413 disagrees, we maybe could close the issue as it seems fixed by `0.9.0-beta.4.n008.hb20ad22` ?

**Comment by consideRatio** [comment] 2020-03-13 06:07
I think this is caused by a lot of complexity in helm, and there are multiple issues combined.

- We should use the --atomic flag when we upgrade with helm, it will ensure that an upgrade that fails return us to the same state as before
- we should use --force to allow helm to do an operation on the autohttps deployment, but it may be that we are required to manually delete the autohttps deployment first instead, this is untested when upgrading from 0.8.2 with a running autohttps deployment as far as i know, and feedback if it is enough with --force would be great.

**Comment by manics** [comment] 2020-03-14 14:33
If you're using helm 3 `--force` behaves differently and may cause something else to fail. I imagine it would be fine on Helm 2 though.

**Comment by consideRatio** [comment] 2020-03-17 16:00
@manics, I think we _need_ to use something like force also on Helm 3, either that or manually deleting k8s resources before we upgrade. I'm currently leaning towards suggesting the use of `--atomic --force` as options during the upgrade for both helm2 and 3.

**Comment by manics** [comment] 2020-03-17 16:21
My experience of `--force` on helm 3 is it leads to other problems with obscure error messages, even with just minor config changes.

Helm 3 is still in preview mode for Z2JH though, and we don't have an upgrade path from Helm 2 to 3 yet. This hopefully means the number of helm 3 users with a 0.8.2 deployment will be fairly small, with an even smaller number using `autohttps`. To keep things simple we could say
- Helm 3 users: `kubectl delete` the resource
- Helm 2 users: definitely `--force`, also `--atomic` if you recommend it (I haven't tried it)

?

**Comment by consideRatio** [comment] 2020-03-17 17:05
> My experience of `--force` on helm 3 is it leads to other problems with obscure error messages, even with just minor config changes.

Awww okay I'm sad to hear that, thanks for sharing your experience about this! Okay, so perhaps not default to `--force` i helm 3 then.

/cc: @jhamman

**Comment by betolink** [comment] 2020-04-24 04:20
I just ran into this issue, my 0.8.2 deployment was working fine and when I created a new cluster and tried to install 0.9.0 it just didn't work using the same configuration. Maybe related to the letsencrypt service. I'm using Helm v2

**Comment by betolink** [comment] 2020-04-24 04:38
After some troubleshooting I've found that the first time letsencript tries to issue the certs it fails because the domain is not automatically configured to point to the loadbalancer(AWS), duh! so I had to scale the autohttps deployment to 0, make the change on Route53: point my domain to the loadbalancerIP and then scale it back to 1.... then it worked.

**Comment by consideRatio** [comment] 2020-10-07 22:54
Quite a bit is discussed in this issue, but to conclude:
1. Helm can be troublesome during upgrade, and sometimes it requires manually cleaning up resources after a `helm upgrade` has failed. To avoid this in helm2 and helm3 I'd strongly recommend using the `--cleanup-on-fail` flag.
2. The autohttps/letsencrypt/ACME issues are resolved in the latest development release of the chart.

**Closed by consideRatio** 2020-10-07 22:54 UTC
