### ISSUE TITLE
Feature: Use leader election to implement fencing of multiple hub replicas

### ISSUE THREAD

**Issue by chancez** [jupyterhub/zero-to-jupyterhub-k8s#1649] opened 2020-04-29 18:40 UTC
### Proposed change
I understand that running multiple active copies of the hub component isn't supported due to the in-memory state each holds. I also would like to have a simple active/passive based failover model so I can automate upgrades of nodes and clusters without having to modify the PDB or force evict the hub pod.

I believe this can be achieved using leader election using configmaps/secrets, much like other Kubernetes controllers/operators do. This could probably be implemented in python or a bash script which runs as part of the hub pod's entrypoint. 

The way it works is that each hub pod replica would startup and attempt to get the configmap, create it if it does not exist, and update it if it does. Only one pod will succeed in creating it, and that will be the first leader. 

The content of the configmap only needs to contain the current "leader's" pod name and a timestamp of the last time the leader refreshed the lock. The timestamp acts as a way for other pods to detect if the leader has failed, and the pod name is to determine what pod is currently the leader, so each pod can determine if they're leader or not.

Each replica will only update the configmap if their own podname is in the configmap, otherwise they simply periodically query the configmap to see if the previous leader has stopped updating it. After a certain amount of time, if it's not updated, the "followers" attempt to gain leadership by updating the configmap with their own pod name and the current time. This will only succeed for one pod due to updates being a compare and swap operation. 

If the current leader fails to update the configmap in a timely fashion, it will notice it's pod name is no longer in the configmap, marking the end of it's leadership, triggering a shutting down of jupyterhub for that pod, and exiting so that the pod can restart and begin attempting to gain the leadership lock again.

A few notes:
- This requires jupyterhub is using a non-sqlite backed database. Otherwise the other copies of the pod would be stuck pending until the existing one dies since the PVC would already be mounted.
- The hub pod would need RBAC permissions to manage the configmap or secret for it's leader leader election lock, but that can be scoped fairly narrowly.

### Alternative options
Make jupyterhub HA capable by removing any in-memory shard state to an external system.

### Who would use this feature?
Anyone running jupyterhub with the need to restart/replace the node that the hub pod runs on.

**Comment by betatim** [comment] 2020-05-03 08:33
I like the idea of having a "shadow" hub as a stepping stone towards having full "multi hub" capabilities.

It sounds like we could use readyness probes to have traffic routed to the leader (it's readyness probe succeeds, all follower's readyness probes fail). Is that how others do it?

I think a lot of preparation work will have to happen in JupyterHub itself first. In particular how the shadow hub would keep its state "in sync" with the "leader" hub. Or maybe the shadow hub has an empty in memory state until it becomes the leader. In this case the question is if updating/creating all the in memory state is faster than starting a new pod. These are things to discuss in the JupyterHub repo (I think).

The in memory state can't be moved outside (without a lot of work) as it is in memory as an optimisation for querying a DB.

**Comment by chancez** [comment] 2020-05-04 16:33
> It sounds like we could use readyness probes to have traffic routed to the leader (it's readyness probe succeeds, all follower's readyness probes fail). Is that how others do it?

I hadn't thought much about this part yet, but that sounds correct.

> Or maybe the shadow hub has an empty in memory state until it becomes the leader. 
That was my thinking.

> The in memory state can't be moved outside (without a lot of work) as it is in memory as an optimisation for querying a DB.

Sure, doesn't really matter too much since it has no effect on this approach.

**Comment by manics** [comment] 2020-05-04 16:40
One default setting you'll have to workaround is that JupyterHub stores it database in sqlite on a PVC. Most kubernetes PersistentVolume classes can only be mounted by either a single pod in read-write mode, or by multiple pods as read-only. Kubernetes would therefore block your standby pod from starting until the PVC could be mounted.

Some work has been done on supporting PostgreSQL which would allow multiple hubs on standby, but I'm not sure what the current state is.

**Comment by chancez** [comment] 2020-05-04 17:00
@manics Good point. I'm actually using an external RDS Postgres, and using a non-sqlite DB would be required for this to work. I'll update the original issue to mention this!

**Comment by consideRatio** [comment] 2020-10-08 00:41
A hub that isn't a leader, what would it do? Wait to startup? Be in a not ready state to not hog traffic from the hub k8s service? I think this wouldn't work so well until JupyterHub as software, even when using an external DB, is currently designed as a server that is assuming to be working alone against the DB.

This is discussed in JupyterHub's repo: https://github.com/jupyterhub/jupyterhub/issues/1932#issuecomment-393147672
It is also discussed in: https://github.com/jupyterhub/team-compass/issues/338

I'll close this issue as a duplicate of these efforts, even though the idea of using k8s native leader election and such, the core issues remain to be addressed first I believe.

**Closed by consideRatio** 2020-10-08 00:41 UTC
