### ISSUE TITLE
Permission denied writing into /srv/jupyterhub/jupyterhub_cookie_secret 

### ISSUE THREAD

**Issue by kavemun** [jupyterhub/zero-to-jupyterhub-k8s#1049] opened 2018-12-05 08:02 UTC
I'm following the instructions on zero-to-jupyterhub,
I ran into some error starting jupyterhub.

```
$ sudo helm upgrade --install $RELEASE jupyterhub/jupyterhub   --namespace $NAMESPACE    --version 0.7.0   --values config.yaml
Release "jhub" does not exist. Installing it now.
NAME:   jhub
LAST DEPLOYED: Wed Dec  5 15:54:00 2018
NAMESPACE: jhub
STATUS: DEPLOYED

RESOURCES:
==> v1/Secret
NAME        AGE
hub-secret  1s

==> v1/ConfigMap
hub-config  1s

==> v1/PersistentVolumeClaim
hub-db-dir  1s

==> v1beta1/Role
hub  1s

==> v1/Service
hub           1s
proxy-public  1s
proxy-api     1s

==> v1beta2/Deployment
hub    1s
proxy  1s

==> v1/ServiceAccount
hub  1s

==> v1beta1/RoleBinding
hub  1s

==> v1beta1/PodDisruptionBudget
hub    1s
proxy  1s

==> v1/Pod(related)

NAME                    READY  STATUS             RESTARTS  AGE
hub-7d4cf754b7-8cvpl    0/1    Pending            0         1s
proxy-85c9b4dbb8-xstj5  0/1    ContainerCreating  0         1s


NOTES:
Thank you for installing JupyterHub!

Your release is named jhub and installed into the namespace jhub.

You can find if the hub and proxy is ready by doing:

 kubectl --namespace=jhub get pod

and watching for both those pods to be in status 'Ready'.

You can find the public IP of the JupyterHub by doing:

 kubectl --namespace=jhub get svc proxy-public

It might take a few minutes for it to appear!

Note that this is still an alpha release! If you have questions, feel free to
  1. Read the guide at https://z2jh.jupyter.org
  2. Chat with us at https://gitter.im/jupyterhub/jupyterhub
  3. File issues at https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues

```

and then 

```
$ kubectl --namespace=jhub get pod
NAME                     READY     STATUS             RESTARTS   AGE
hub-7d4cf754b7-8cvpl     0/1       CrashLoopBackOff   1          25s
proxy-85c9b4dbb8-xstj5   1/1       Running            0          25s


```

logs for hub

```
$ kubectl logs hub-7d4cf754b7-8cvpl -n jhub
[I 2018-12-05 15:36:39.591 JupyterHub app:1667] Using Authenticator: dummyauthenticator.dummyauthenticator.DummyAuthenticator
[I 2018-12-05 15:36:39.592 JupyterHub app:1667] Using Spawner: kubespawner.spawner.KubeSpawner
[I 2018-12-05 15:36:39.592 JupyterHub app:1053] Writing cookie_secret to /srv/jupyterhub/jupyterhub_cookie_secret
[E 2018-12-05 15:36:39.594 JupyterHub app:1952]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1949, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1673, in initialize
        self.init_secrets()
      File "/usr/local/lib/python3.6/dist-packages/jupyterhub/app.py", line 1055, in init_secrets
        with open(secret_file, 'w') as f:
    PermissionError: [Errno 13] Permission denied: '/srv/jupyterhub/jupyterhub_cookie_secret'

```

how do i enable permission to write into /srv/jupyterhub directory?

Thanks

**Comment by minrk** [comment] 2018-12-05 10:36
how have you deployed kubernetes? This suggests that the volume provisioner creates volumes owned and writeable only by root, which is ~never the right thing to do, but a common problem. It's not too hard to fix this for the hub volume by manually modifying the permissions on the volume after creation, but if you have user volumes, this is going to be a huge headache before, so I'd suggest fixing the volume provisioner. I'd look around for "[my cloud provider] persistent volume root permissions" for a solution.

**Comment by minrk** [comment] 2018-12-06 10:04
hub-db-dir should be mounted at /srv/jupyterhub, so permissions in the persistent volume would be the relevant ones.. Can you verify that `/srv/jupyterhub` is mounted from the volume `hub-db-dir`?

**Comment by kavemun** [comment] 2018-12-07 08:21
@minrk  looks like it? although i may be wrong, quite new to this

```
$ kubectl -n jhub describe po
Name:           hub-77b6cc9d9c-5268c
Namespace:      jhub
Node:           10.60.1.27/10.60.1.27
Start Time:     Fri, 07 Dec 2018 22:52:08 +0800
Labels:         app=jupyterhub
                component=hub
                hub.jupyter.org/network-access-proxy-api=true
                hub.jupyter.org/network-access-proxy-http=true
                hub.jupyter.org/network-access-singleuser=true
                pod-template-hash=3362775857
                release=jhub
Annotations:    checksum/config-map=9f1ef933cd68c737e4dee671015601208f69728c752a0a41e9b8e51e2cf7da2f
                checksum/secret=fbbd561d39e190819f885843abf4eb4003a6ebba3de41835f4d6e8beacc0bd33
                cni.projectcalico.org/podIP=10.2.5.39/32
                kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"jhub","name":"hub-77b6cc9d9c","uid":"80647b87-f9ee-11e8-bf6b-0050569a0cd3","apiVe...
                prometheus.io/path=/hub/metrics
                prometheus.io/scrape=true
Status:         Running
IP:             10.2.5.39
Created By:     ReplicaSet/hub-77b6cc9d9c
Controlled By:  ReplicaSet/hub-77b6cc9d9c
Containers:
  hub:
    Container ID:  docker://b421180a9f0c1fa4da1ab37a3691cb02570f84298783474ba9fabfb63e0dcd37
    Image:         jupyterhub/k8s-hub:0.7.0
    Image ID:      docker-pullable://jupyterhub/k8s-hub@sha256:7b7546357b33d6f603035d04c40e3facff0ebb4b5f7b7446c8303f44b81ae5a4
    Port:          8081/TCP
    Command:
      jupyterhub
      --config
      /srv/jupyterhub_config.py
      --upgrade-db
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Sat, 08 Dec 2018 00:00:23 +0800
      Finished:     Sat, 08 Dec 2018 00:00:25 +0800
    Ready:          False
    Restart Count:  18
    Requests:
      cpu:     200m
      memory:  512Mi
    Environment:
      SINGLEUSER_IMAGE:        jupyterhub/k8s-singleuser-sample:0.7.0
      POD_NAMESPACE:           jhub (v1:metadata.namespace)
      CONFIGPROXY_AUTH_TOKEN:  <set to the key 'proxy.token' in secret 'hub-secret'>  Optional: false
    Mounts:
      /etc/jupyterhub/config/ from config (rw)
      /etc/jupyterhub/secret/ from secret (rw)
      **/srv/jupyterhub from hub-db-dir (rw)**
      /var/run/secrets/kubernetes.io/serviceaccount from hub-token-ctj9x (ro)

```

the admin is on leave today so i can't check with him regarding the ceph configurations, and i will be on leave from monday onwards... will come back to this problem when i get back... any pointers or advice would be great. 

Thanks again @minrk

**Comment by minrk** [comment] 2018-12-10 13:53
If it is mounted, as it looks like it is, then the issue is indeed permissions in the volume. This would mean that the `hub-db-dir` volume is not writable by the uid that is running the hub (1000 by default, I believe)

**Comment by canhtran** [comment] 2019-01-16 09:30
I'm also facing the same issue. Do you have any solutions @kavemun ? Thanks in advance

**Comment by kavemun** [comment] 2019-01-17 02:31
@canhtran Sorry, our system is going through some major migration and i haven't got the chance to look at this issue yet. Last i check, like what @minrk says, it looks like an issue with the volumes. If you have any updates, do keep me posted too. Thanks.

**Comment by canhtran** [comment] 2019-01-19 16:40
Hi @kavemun, I have found the solution for it. what @minrk said is corrected. It's an issue with the volumes. By default, the k8s will create data directory under root so that jupyterhub cannot write. 
I added the uid and fsGid into 0 which is root in config.yaml and it works

```
hub:
  uid: 0
  fsGid: 0
```

**Comment by pr0xxy** [comment] 2019-08-06 10:59
> Hi @kavemun, I have found the solution for it. what @minrk said is corrected. It's an issue with the volumes. By default, the k8s will create directory under root so that jupyterhub cannot write.
> I added the uid and fsGid into 0 which is root in config.yaml and it works
> 
> ```
> hub:
>   uid: 0
>   fsGid: 0
> ```

This fixed the "Permission denied writing into /srv/jupyterhub/jupyterhub_cookie_secret" issue I was seeing. Thanks!

**Comment by Aisuko** [comment] 2019-11-25 07:53
Thanks for you all made a discussion. I have a consideration on this. If I just want to no root user of the container. How should I do it?

**Comment by consideRatio** [comment] 2019-11-30 14:14
@Aisuko i think the hub containers etc are run as non-root already since #1280, we are aiming to not run as root throughout the helm chart.

The original issue was one relating to the kubernetes cluster itself, and how storage was provisioned I believe. I'm closing this issue, feel free to open a new.

**Closed by consideRatio** 2019-11-30 14:14 UTC

**Comment by Aisuko** [comment] 2019-12-02 02:54
I see, thanks.

**Comment by lormidorido** [comment] 2020-07-19 04:11
Hi guys

I am new to kubernetes. The solution to this problem appears to be to edit the config.yaml file. Where is that file located?

Many thanks

**Comment by consideRatio** [comment] 2020-07-19 04:42
@lormidorido It's a configuration file for the Helm chart you should create yourself, which is part of what you do when you follow the guide at http://z2jh.jupyter.org/

**Comment by lormidorido** [comment] 2020-07-19 18:33
Thanks @consideRatio! Much appreciated your swift response ;)

**Comment by lormidorido** [comment] 2020-07-20 09:43
I run:

[root@master-01 jhub]# helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
"jupyterhub" has been added to your repositories
[root@master-01 jhub]# helm repo update
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "jupyterhub" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete.
[root@master-01 jhub]# RELEASE=jhub
[root@master-01 jhub]# NAMESPACE=jhub[root@master-01 jhub]# helm upgrade --install $RELEASE jupyterhub/jupyterhub --namespace $NAMESPACE --version=0.9.1 --values config.yaml
Release "jhub" does not exist. Installing it now.
Error: timed out waiting for the condition

I have set the time out to 1 hour, still same outcome. It seems to hang. It creates the pods below and that is it.

kubectl --namespace=jhub get pod
NAME                       READY     STATUS    RESTARTS   AGE
hook-image-awaiter-hnzng   1/1       Running   0          2m
hook-image-puller-4bkb4    1/1       Running   0          2m
hook-image-puller-lgnr4    1/1       Running   0          2m
hook-image-puller-rfnv2    1/1       Running   0          2m
hook-image-puller-rh4xg    1/1       Running   0          2m

[root@master-01 jhub]# cat config.yaml
proxy:
  secretToken: "f77fd3605c36991e4d0e870caad9f00da181dd7293cf78bee2b713c6473d9c5c"
hub:
  uid: 0
  fsGid: 0

[root@master-02 ~]# kubectl logs hook-image-awaiter-hnzng -n jhub
2020/07/20 09:33:45 4 of 10 nodes currently has the required images.

It keeps output the line above in the log till the installation times out.

logs empty for the other 4 pods.

Any help much appreciated!

Thanks

**Comment by consideRatio** [comment] 2020-07-20 09:49
Its not sustainable interaction pattern to ask/answer for help in a closed issue. For help questions, see the discourse.jupyter.org forum if. Also please use code blocks to ensure your configuration formats properly in markdown (google: markdown code block).

**Comment by lormidorido** [comment] 2020-07-20 09:50
okidoki

**Comment by meeseeksmachine** [comment] 2021-02-05 11:59
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/crashloopbackoff-due-to-permissionerror-errno-13-permission-denied-srv-jupyterhub-jupyterhub-cookie-secret/7820/1

**Comment by meeseeksmachine** [comment] 2021-02-05 12:19
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/crashloopbackoff-due-to-permissionerror-errno-13-permission-denied-srv-jupyterhub-jupyterhub-cookie-secret/7820/3
