### ISSUE TITLE
autohttps pod unable to obtain certificate

### ISSUE THREAD

**Issue by taylorgibson** [jupyterhub/zero-to-jupyterhub-k8s#2818] opened 2022-07-29 18:56 UTC
I’ve been attempting to set up a new jupyterhub cluster on GCP using the Z2JH guide, and it’s been unable to obtain a certificate from Let’s Encrypt to allow for an https connection. I’ve had this working on an older version of jupyterhub about 2 years ago (and the Z2JH guide) but no luck in recreating the magic on more recent versions. I know the domain name (datahub.ncssm.edu) has had time to resolve to the IP address, as it’s had 72 hours and I’ve been able to verify that I can reach the server via domain name using http.

I’ve configured the `config.yaml` file to include:

```
proxy:
  https:
    enabled: true
    hosts:
      - datahub.ncssm.edu
    letsencrypt:
      contactEmail: <removed>@ncssm.edu
```

It successfully creates the `autohttp`s pod, but when I run `kubectl logs <podname>` I see the following message:

```Defaulted container "traefik" out of: traefik, secret-sync, load-acme (init)
time="2022-07-29T18:28:17Z" level=info msg="Configuration loaded from file: /etc/traefik/traefik.yaml"
time="2022-07-29T18:28:17Z" level=warning msg="Traefik Pilot is deprecated and will be removed soon. Please check our Blog for migration instructions later this year."
time="2022-07-29T18:28:17Z" level=warning msg="No domain found in rule PathPrefix(`/`), the TLS options applied for this router will depend on the SNI of each request" entryPointName=https routerName=default@file
time="2022-07-29T18:28:36Z" level=error msg="Unable to obtain ACME certificate for domains \"datahub.ncssm.edu\" : unable to generate a certificate for the domains [datahub.ncssm.edu]: error: one or more domains had a problem:\n[datahub.ncssm.edu] acme: error: 400 :: urn:ietf:params:acme:error:connection :: 34.86.203.110: Fetching http://datahub.ncssm.edu/.well-known/acme-challenge/ZmJjOqz5lSX7A3W6xMJLlZzI9qxaIFb1VXkGDjRyxV8: Timeout during connect (likely firewall problem)\n" providerName=default.acme
```

Is this a known issue? I don't see an open issue that matches up.

It seems like it’s not able to reach the server to complete the challenge, is that right? If so, any ideas on how to correct this issue?

If helpful, I’m using helm chart version `1.1.3-n743.h730f014f` but I had the same issue on version `1.1.3-n610.h455ae516` (hoped that using a newer version may fix this issue.

**Comment by manics** [comment] 2022-07-29 20:58
This looks like a duplicate of https://discourse.jupyter.org/t/autohttps-pod-unable-to-obtain-lets-encrypt-certificate/15141

**Closed by manics** 2022-07-29 20:58 UTC

**Comment by consideRatio** [comment] 2022-07-30 09:19
Here are a bunch of related issues:

## Related

- https://github.com/traefik/traefik/issues/8803
- #2150
- #2431
- #2818
- #2601 (this issue)

Here is a workaround described:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2601#issuecomment-1127600794

The issue is that GKE isn't so fast to set up networking for freshly started pods it seems.

**Comment by taylorgibson** [comment] 2022-07-30 11:59
Thank you @consideRatio for that tip. The workaround in #2601 resolved the issue. Thanks for the helpful links.

**Comment by consideRatio** [comment] 2022-07-30 12:57
Thanks @taylorgibson for following up and verifying that and your thorough writeup about the issue!
