### ISSUE TITLE
custom spawner docs are outdated

### ISSUE THREAD

**Issue by GergelyKalmar** [jupyterhub/zero-to-jupyterhub-k8s#1607] opened 2020-03-23 17:22 UTC
It seems that if one is using the ``jupyter-labhub`` spawner (as per the [documentation](https://zero-to-jupyterhub.readthedocs.io/en/latest/customizing/user-environment.html#use-jupyterlab-by-default)) the spawns fail with an import error with the latest Helm chart and latest base-notebook image. Without the ``extraConfig`` parts it seems to be working fine though. This may be related to the fact that JupyterHub support is now built into JupyterLab [directly](https://github.com/jupyterhub/jupyterlab-hub). Perhaps the documentation could be updated accordingly.

**Comment by consideRatio** [comment] 2020-03-26 10:03
Yes! @GergelyKalmar would you like to submit a PR where that customization part is removed, along with the outdated note just below that a jupyterhub extension is pre-installed?

The only thing needed now is the default url being /lab I think.

**Comment by dkipping** [comment] 2020-05-04 08:22
Only setting
```
singleuser:
  defaultUrl: '/lab'
```
didn't work for me anymore.

As noted in the new jupyterlab docs, one should try:
```
hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.default_url = '/lab'
```
But this is correctly mapped in the helm chart. Am I missing something here?

**Comment by GergelyKalmar** [comment] 2020-05-05 11:19
Ah, I forgot that I'm using a custom base image with a newer jupyterlab (v2.0.1). I think this change will only have to be made when migrating to jupyterlab v2+. I'm not sure what version Z2JH is at the moment by default.

**Comment by consideRatio** [comment] 2020-05-05 11:31
Im using juoyterlab 2.1 on z2jh i think, it works. Can you upgrade your jupyterhub version and see?

**Comment by dkipping** [comment] 2020-05-05 11:43
It was caused by the `cmd:` parameter of the `singleuser` object.
We had overwritten the parameter as `cmd: null` as a side effect of granting sudo rights for the users.
I found the solution in a discussion on the sudo granting with updated configuration examples for jlab 2.1: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/562#issuecomment-606941223

Working config:
```
singleuser:
  extraEnv: 
    GRANT_SUDO: "yes"
    NOTEBOOK_ARGS: "--allow-root"
  uid: 0
  cmd: start-singleuser.sh
  defaultUrl: "/lab"
```

So the key is to change the parameter to `cmd: start-singleuser.sh`

Would you regard the combination of granting sudo and setting jupyterlab as something common? I did not find documentation on how to grant sudo, it might make sense to add an updated documentation section on that, which also mentions the side effects of the `cmd` parameter (of which I also only have a partial overview though).

**Comment by consideRatio** [comment] 2020-05-05 11:59
> Would you regard the combination of granting sudo and setting jupyterlab as something common? I did not find documentation on how to grant sudo, it might make sense to add an updated documentation section on that, which also mentions the side effects of the cmd parameter (of which I also only have a partial overview though).

Absolutely, worth noting is that the environment variables and script we are using assumes functionality from the https://github.com/jupyter/docker-stacks images, and that how to start jupyterlab also has changed a bit over time making the `cmd` part need adjustments in the past.

Also note that I think it may be relevant to set the `gid: 100` next to `uid: 0`, with a SUDO user setup. This relates to a change since Kubernetes 1.14 I think ^^.

**Comment by GergelyKalmar** [comment] 2020-05-05 12:03
Ah yes, the sudo issue. I've been there too. I didn't have the patience to work around it but would definitely see value in being able to enable sudoing in the regular terminal of an instance. In some cases it could make debugging some issues much more convenient. For one, I think you can't even cat system logs with the regular user.

When I was researching it there seemed to be a lot of people trying various ways to sudo in JupyterHub, asking for password for the jovyan user and such. I could see this to be a feature people may want to use together too.

**Comment by consideRatio** [comment] 2020-10-07 23:14
Closing issue, the jupyter-labhub described in the original issue have been removed now

**Closed by consideRatio** 2020-10-07 23:14 UTC
