### ISSUE TITLE
Google OAuth and Whitelisting

### ISSUE THREAD

**Issue by celine168** [jupyterhub/zero-to-jupyterhub-k8s#1345] opened 2019-08-01 19:13 UTC
Hello! I cannot whitelist specific email addresses while using Google OAuth at the same time. The [documentation](https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html#adding-a-whitelist) makes it sound possible, but any user from the same organization could log in, regardless if the whitelist lists them or not.

Part of our `config.yaml` file looks like this:
```
auth:
  type: google
  google:
    clientId: "<client id>"
    clientSecret: "<client secret>"
    callbackUrl: "<domain/hub/oauth_callback>"
    hostedDomain: "<domain>"
    loginService: "<organization>"
  whitelist:
    users:
      - <username>@email.edu

hub:
  extraConfig:
    jupyterlab: |
      c.Spawner.cmd = ['jupyter-labhub']
```
I also tried to remove the `@email.edu` part of each user, but that doesn't seem to work either.
Extra info: our cluster is set up so that nginx forwards public IP addresses to the LoadBalancers' `EXTERNAL-IP`'s. Not sure if that would make a difference.

**Comment by celine168** [comment] 2019-08-02 22:38
Turns out it was working, with the caveat that users who previously logged in but aren't whitelisted could still log in. 

We kept testing with email addresses which had already logged in, so it appeared that there was an issue.

**Comment by betatim** [comment] 2019-08-05 06:01
Thanks for reporting that you fixed it. I will close this issue as it is resolved.

You had posted a duplicate of this on discourse here https://discourse.jupyter.org/t/google-oauth-with-whitelist/1751 could you mark that as resolved as well? (In general it is considered a bit rude to post the same question in multiple places. If there is new information or a specific aspect that is better discussed in one of the places it is fine if you highlight the difference otherwise the people who might know the answer and read all the places get a deja-vu feeling and/or start treating it as noise.)

**Closed by betatim** 2019-08-05 06:01 UTC

**Comment by celine168** [comment] 2019-08-07 01:06
I'm sorry, I'll take note of that next time. Thank you for explaining.
