### ISSUE TITLE
jupyterhub strict linting fails

### ISSUE THREAD

**Issue by baboune** [jupyterhub/zero-to-jupyterhub-k8s#1676] opened 2020-05-20 12:09 UTC
### Bug description

```
$ helm lint --strict jupyterhub
==> Linting jupyterhub
[ERROR] templates/: template: gaia-jupyterhub/templates/scheduling/user-scheduler/rbac.yaml:8:8: executing "gaia-jupyterhub/templates/scheduling/user-scheduler/rbac.yaml" at <include "jupyterhub.labels" .>: error calling include: template: gaia-jupyterhub/templates/_helpers.tpl:150:14: executing "jupyterhub.labels" at <include "jupyterhub.componentLabel" .>: error calling include: template: gaia-jupyterhub/templates/_helpers.tpl:108:18: executing "jupyterhub.componentLabel" at <.componentLabel>: map has no entry for key "componentLabel"

Error: 1 chart(s) linted, 1 chart(s) failed
```

#### Expected behaviour

Lint with "strict" flag should succeed without any ERROR.

`[ERROR] templates/.`

#### Actual behaviour

Lint failed with an error:
```
: error calling include: template: gaia-jupyterhub/templates/_helpers.tpl:108:18: executing "jupyterhub.componentLabel" at <.componentLabel>: map has no entry for key "componentLabel"
```
Based on how labels are generated this error may be expected? Or it may be a helm bug?

### How to reproduce

1. Clone the git repo
2. cd zero-to-jupyterhub-k8s
3. helm lint --strict ./jupyterhub

```
✗ helm version
version.BuildInfo{Version:"v3.2.0", GitCommit:"e11b7ce3b12db2941e90399e874513fbd24bcb71", GitTreeState:"clean", GoVersion:"go1.13.10"}
```

### Your personal set up

 - OS:
 
   OSX 10.14.16
 - Version:
 
    jupyterhub 0.9.0, 0.8.2
 - Configuration:
 
        helm "v3.2.0"

**Comment by consideRatio** [comment] 2020-05-23 12:25
I could reproduce this, and I've tracked it down to statements we have like this one:

```yaml
{{- $component := .componentLabel | default $parent | default $file }}
```

We check for .componentLabel, but if it doesn't exist, we fallback to something that does. `helm lint --strict` will spot that we even asked what the value of `.componentLabel` outside of a `if` statement, and that made us run into an error.

If this would be ignored, there would pop up another one where we used `default` etc. And I don't want to workaround this just to please helm lint because it would make the helper functions even more complicated to read.

If we could make the helm linter ignore certain errors etc that would be something I think could make sense to do though.

**Comment by consideRatio** [comment] 2020-05-23 12:53
@baboune do you know if complying with `helm lint --strict` is an requirement for something, like being published on helm hub or similar?

**Comment by baboune** [comment] 2020-05-23 14:15
I do not know if using `helm lint strict` is a requirement for being published in general. 

Code wise it looks OK, which is why I am wondering if this could be an helm bug?

**Comment by baboune** [comment] 2020-05-23 14:23
Opened an issue on helm https://github.com/helm/helm/issues/8192.

**Comment by consideRatio** [comment] 2020-05-23 15:11
I experimented a bit on complying with `helm lint --strict`, and this is almost enough: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/1681

The labels have meaning, and making changes is a bit messy. Best practices have changed across time for helm charts have changed as well etc, so it is quite messy.

**Comment by baboune** [comment] 2020-05-23 15:25
I like the changes, the code is clearer 👍

**Comment by consideRatio** [comment] 2020-10-08 00:59
I'm closing this as `helm lint --strict` seems like too strict for us to want to enforce. I would have loved complying with a slightly less strict linting, but I believe it caused a bit too much challenges in our template logic.

**Closed by consideRatio** 2020-10-08 00:59 UTC

**Comment by consideRatio** [comment] 2020-10-27 18:12
Apparently they lowered the requirements, we are now passing `helm lint --strict` with helm 3.3.4

**Comment by baboune** [comment] 2020-10-27 21:38
Excellent!
Thanks.
