### ISSUE TITLE
Add schema.yaml validation for extraFiles.data structure

### ISSUE THREAD

**Issue by roelbaz** [jupyterhub/zero-to-jupyterhub-k8s#2095] opened 2021-03-11 19:02 UTC
### Bug description

Template parsing error of the extraFile mountPath in:

jupyterhub/templates/_helpers.tpl:382:29: executing "jupyterhub.extraFiles.validate-file" at $file_details.mountPath>: can't evaluate field mountPath in type string                         

This was introduced in this PR: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/pull/2006

This is in versions  0.11.1-n113.hc841983b through 0.11.1-n301.hc86268b1 (Didn't try em all obviously, but those two are the 'bookends')

#### Expected behaviour

No parsing complaints from the _helpers.tpl

#### Actual behaviour

ubuntu@jhub-controller:~/jhub/kubernetes$
```
ubuntu@jhub-controller:~/jhub/kubernetes$ helm upgrade --cleanup-on-fail   --install jhub jupyterhub/jupyterhub   --namespace jhub   --create-namespace   --version=0.11.1-n301.hc86268b1
Error: UPGRADE FAILED: template: jupyterhub/templates/singleuser/secret.yaml:9:9: executing "jupyterhub/templates/singleuser/secret.yaml" at <include "jupyterhub.extraFiles.data" .Values.singleuser.extraFiles>: error calling include: template: jupyterhub/templates/_helpers.tpl:343:8: executing "jupyterhub.extraFiles.data" at <include "jupyterhub.extraFiles.data.withNewLineSuffix" .>: error calling include: template: jupyterhub/templates/_helpers.tpl:336:12: executing "jupyterhub.extraFiles.data.withNewLineSuffix" at <include "jupyterhub.extraFiles.validate-file" (list $file_key $file_details)>: error calling include: template: jupyterhub/templates/_helpers.tpl:382:29: executing "jupyterhub.extraFiles.validate-file" at <$file_details.mountPath>: can't evaluate field mountPath in type string

```
### How to reproduce

Near as I can tell, a standard config.yaml for helm3 is going to provoke this. 

- Note that I did upgrade the cluster from helm 2 to 3. (
- Basic cluster as described in the install guide with the optional dedicated user pool.

### Your personal set up

 - OS:
 ubuntu@jhub-controller:~/jhub/kubernetes$ cat /etc/issue
Ubuntu 20.04.1 LTS \n \l
 
- <details><summary>Configuration</summary>
Jupyterhub 1.3.0
Helm chart version: 0.11.1-n301.hc86268b1 (march 11th) but tried all the way back to 0.11.1-n113.hc841983b  (feb 1st) when the aforementioned PR got introduced. 

jupyterhub_config.py is unmodified from what is in the helm chart.

```
ubuntu@jhub-controller:~/.config/helm$ cat repositories.yaml 
apiVersion: v1
generated: "2021-02-09T20:21:27.59853531Z"
repositories:
- caFile: ""
  cache: /home/ubuntu/.helm/repository/cache/stable-index.yaml
  certFile: ""
  keyFile: ""
  name: stable
  password: ""
  url: https://charts.helm.sh/stable
  username: ""
- caFile: ""
  cache: /home/ubuntu/.helm/repository/cache/local-index.yaml
  certFile: ""
  keyFile: ""
  name: local
  password: ""
  url: http://127.0.0.1:8879/charts
  username: ""
- caFile: ""
  cache: /home/ubuntu/.helm/repository/cache/jupyterhub-index.yaml
  certFile: ""
  keyFile: ""
  name: jupyterhub
  password: ""
  url: https://jupyterhub.github.io/helm-chart/
  username: ""
```
</details>

- <details><summary>Logs</summary>
```
Error: UPGRADE FAILED: template: jupyterhub/templates/singleuser/secret.yaml:9:9: executing "jupyterhub/templates/singleuser/secret.yaml" at <include "jupyterhub.extraFiles.data" .Values.singleuser.extraFiles>: error calling include: template: jupyterhub/templates/_helpers.tpl:343:8: executing "jupyterhub.extraFiles.data" at <include "jupyterhub.extraFiles.data.withNewLineSuffix" .>: error calling include: template: jupyterhub/templates/_helpers.tpl:336:12: executing "jupyterhub.extraFiles.data.withNewLineSuffix" at <include "jupyterhub.extraFiles.validate-file" (list $file_key $file_details)>: error calling include: template: jupyterhub/templates/_helpers.tpl:382:29: executing "jupyterhub.extraFiles.validate-file" at <$file_details.mountPath>: can't evaluate field mountPath in type string

```
</details>

**Comment by roelbaz** [comment] 2021-03-11 19:03
An prematurely apologies if this an 'obvious' error. Based on my tinkering however I think this is an actual error in _helpers.tpl.

**Comment by consideRatio** [comment] 2021-03-11 19:20
@roelbaz I can't reproduce this, and feel quite confident that the helm chart is given some configuration that has been invalid.

It smells to me like an issue caused by for example terraform modifying the config in a faulty way. If it were an issue, it should be able to reproduce like this:

```
helm template hub1 jupyterhub --repo=https://jupyterhub.github.io/helm-chart/ --version=0.11.1-n301.hc86268b1
```

Technically, I think this is an error caused by a config like...

```yaml
hub:
  extraFiles:
    test: "hi"
```

I can reproduce it like this...

```
helm template hub1 jupyterhub --repo=https://jupyterhub.github.io/helm-chart/ --version=0.11.1-n301.hc86268b1 --set hub.extraFiles.test=string-here
```

So, I assume this is a misconfiguration, and potentially caused by an external tool out of this helm charts control. I'll go ahead and close it for now but do followup if you can pinpoint this as an issue with the Helm chart.

**Comment by roelbaz** [comment] 2021-03-11 19:25
First of this is without *any* reference in the config.yaml to singleuser.extraFiles. (ie, not included whatsoever.)

But given your suggestions in your response I'll tinker some and see if I can reproduce. Ultimately I'm after using extraFiles, but at this point I'm not even attempting that.

**Comment by roelbaz** [comment] 2021-03-11 19:26
Also thanks a whole bunch replying so quickly

**Comment by consideRatio** [comment] 2021-03-11 19:30
The error you get is associated with Helm template rendering, so it should be reproducible like...

```shell
$ helm version
version.BuildInfo{Version:"v3.5.0", GitCommit:"32c22239423b3b4ba6706d450bd044baffdcf9e6", GitTreeState:"clean", GoVersion:"go1.15.6"}

# this should work, and does work for me
helm template hub1 jupyterhub --repo=https://jupyterhub.github.io/helm-chart/ --version=0.11.1-n301.hc86268b1
```

**Comment by roelbaz** [comment] 2021-03-11 19:47
Thanks for the help/suggestions. Template command you gave me renders without error. Obviously have to dig, will let you know what I find. 

To be clear the helm config.yaml does work with 0.11.1 and 0.11.1-n082.h437ed29d (ie, just prior to PR #2006)

**Comment by consideRatio** [comment] 2021-03-11 19:50
@roelbaz okay then use `--debug` helm flag and copy paste the values under hub.extraFiles and singleuser.extraFiles as should be listed before the error shows using `--debug`.

**Comment by roelbaz** [comment] 2021-03-11 19:58
I think I got it... it's the --set-files on the commandline screwing things up. I drop the --set-files *and* the extraFiles section in the config.yaml, and it loads.

**Comment by consideRatio** [comment] 2021-03-11 20:04
Hmmm... If you are using --set-file, you should probably use something else than `data`, such as `stringData` or `binaryData`. See https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#hub-extrafiles

**Comment by consideRatio** [comment] 2021-03-11 20:06
You could have been given a better error message for this misconfiguration, so I'm renaming this issue

**Comment by roelbaz** [comment] 2021-03-11 20:13
OK, confirmed my 'stupid' here:

**Comment by consideRatio** [comment] 2021-03-11 20:17
We have a file called schema.yaml, it is a YAML representation of a JSONSchema, which is a format to validate data structures found in JSON/YAML for example.

Here it is:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/c86268b174e70e37fd68168450ea8737db3c8f61/jupyterhub/schema.yaml#L257-L259

To better catch you error, we can trial with...

```
# this should say that `.data` must not be a string before doing anything else
helm template hub1 jupyterhub --repo=https://jupyterhub.github.io/helm-chart/ --version=0.11.1-n301.hc86268b1 --set hub.extraFiles.data=mystring
```

To do so, our extraFiles entry should look more like this instead:

https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/c86268b174e70e37fd68168450ea8737db3c8f61/jupyterhub/schema.yaml#L474-L506

@roelbaz, would you be interested in contributing a PR to fix this, updating schema.yaml to better help users catch this kind of error in the future?

**Comment by roelbaz** [comment] 2021-03-11 20:20
@consideRatio Yes I'll contribute a PR, give me ~24hrs or so.

**Comment by consideRatio** [comment] 2021-03-11 20:23
@roelbaz wiee! Do ping me if you feel stuck!

Also btw I think we are better of by not adding the `description` fields on the properties of `extraFiles` such as `data`, `stringData`, `binaryData`, `mountPath` etc as they are described extensively in the `extraFiles` description field already so I suggest we avoid repeating ourselves.

**Comment by roelbaz** [comment] 2021-03-13 01:41
@consideRatio It'll be a bit more than 24hrs, as usual a bit too optimistic about my actual workload.

**Comment by consideRatio** [comment] 2021-03-13 01:44
:heart: :heart: @roelbaz no preassure!

**Closed** 2021-05-15 15:24 UTC
Labels: maintenance
