### ISSUE TITLE
Jupyterhub pod (Z2JK Helm chart version 0.10.6)  does not start because it can not create the jupyterhub schema , its tables and other database objects when the database is deployed to Google Cloud SQL for Postgress

### ISSUE THREAD

**Issue by markcberman** [jupyterhub/zero-to-jupyterhub-k8s#2333] opened 2021-07-27 19:22 UTC
### Bug description
Jupyterhub pod (Z2JK Helm chart version 0.10.6)  does not start because it can not create the jupyterhub schema , its tables and other database objects when the database is deployed to Google Cloud SQL for Postgress. Here is the error message.

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidSchemaName) no schema has been selected to create in
    LINE 2: CREATE TABLE alembic_version (
                         ^
    
    [SQL: 
    CREATE TABLE alembic_version (
    	version_num VARCHAR(32) NOT NULL, 
    	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
    )

Here is some more context about the issue:

We are trying to redeploy Z2JK from scratch into a GKE development environment due to an accidental deletion of the jupyterhub schema and tables that is running in a shared Google Cloud SQL for Postgres cluster. Unfortunately, there is no reliable backup of the the “jupyterhub” schema, tables and data in our development environment. (We will fix that shortly.)

We deleted all of the Z2JK deployments, stateful sets, jobs, pods, etc from the K8s namespace where Z2JK runs – and as I said the “jupyterhub” schema no longer exists because it was accidentally deleted from our Google Cloud SQL for Postgres cluster.

We re-ran the Helm deployment.

The jupyterhub pod is failing with the following error message which states there is no schema for SQLAlchemy to create the alembic_version table in. Not sure what is going on as the initial Jupyterhub deployment created the “jupyterhub” schema and all of the tables and other database objects. 

#### Expected behaviour
The Jupyterhub pod should automatically recreate it's schema, tables and database objects if the schema is missing from the database.

#### Actual behaviour
Jupyterhub pod does not start because it can not create the jupyterhub schema, it tables and other database objects.  Here is the error message.

sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidSchemaName) no schema has been selected to create in
    LINE 2: CREATE TABLE alembic_version (
                         ^
    
    [SQL: 
    CREATE TABLE alembic_version (
    	version_num VARCHAR(32) NOT NULL, 
    	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
    )

### How to reproduce
Install  Z2JK with a database running in a non-memory datastore (Postgres or any other database compatible with Jupyterhub).
Delete the database.
Delete the hub' deployment -- which in turn will delete the hub's replicaset and pod.
Redeploy Z2JK using the Helm chart. This will result in a new hub deployment, replica set and pod

### Your personal set up

Z2JK helm chart version 0.10.6
GKE 1.17

```
# paste output of `pip freeze` or `conda list` here
```
</details>

- <details><summary>Configuration</summary>

```python
Custom version of Kubespawner and custom version of OAUTH authenticator that works with ping federate.
```
</details>

- <details><summary>Logs</summary>

```
 [I 2021-07-27 10:47:25.221 alembic.runtime.migration migration:155] Context impl PostgresqlImpl.
[I 2021-07-27 10:47:25.221 alembic.runtime.migration migration:158] Will assume transactional DDL.
[E 2021-07-27 10:47:25.236 JupyterHub app:2844]
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2841, in launch_instance_async
        await self.initialize(argv)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 2374, in initialize
        self.init_db()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/app.py", line 1584, in init_db
        self.session_factory = orm.new_session_factory(
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/orm.py", line 880, in new_session_factory
        check_db_revision(engine)
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/orm.py", line 785, in check_db_revision
        alembic.command.stamp(cfg, head)
      File "/usr/local/lib/python3.8/dist-packages/alembic/command.py", line 581, in stamp
        script.run_env()
      File "/usr/local/lib/python3.8/dist-packages/alembic/script/base.py", line 489, in run_env
        util.load_python_file(self.dir, "env.py")
      File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 98, in load_python_file
        module = load_module_py(module_id, path)
      File "/usr/local/lib/python3.8/dist-packages/alembic/util/compat.py", line 184, in load_module_py
        spec.loader.exec_module(module)
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/alembic/env.py", line 88, in <module>
        run_migrations_online()
      File "/usr/local/lib/python3.8/dist-packages/jupyterhub/alembic/env.py", line 82, in run_migrations_online
        context.run_migrations()
      File "<string>", line 8, in run_migrations
      File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/environment.py", line 846, in run_migrations
        self.get_context().run_migrations(**kw)
      File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/migration.py", line 503, in run_migrations
        self._ensure_version_table()
      File "/usr/local/lib/python3.8/dist-packages/alembic/runtime/migration.py", line 442, in _ensure_version_table
        self._version.create(self.connection, checkfirst=True)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/schema.py", line 925, in create
        bind._run_visitor(ddl.SchemaGenerator, self, checkfirst=checkfirst)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1656, in _run_visitor
        visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/visitors.py", line 145, in traverse_single
        return meth(obj, **kw)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 827, in visit_table
        self.connection.execute(
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
        return meth(self, multiparams, params)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
        return connection._execute_ddl(self, multiparams, params)
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1068, in _execute_ddl
        ret = self._execute_context(
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
        self._handle_dbapi_exception(
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
        util.raise_(
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
        raise exception
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
        self.dialect.do_execute(
      File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 593, in do_execute
        cursor.execute(statement, parameters)
    sqlalchemy.exc.ProgrammingError: (psycopg2.errors.InvalidSchemaName) no schema has been selected to create in
    LINE 2: CREATE TABLE alembic_version (
                         ^
    
    [SQL: 
    CREATE TABLE alembic_version (
    	version_num VARCHAR(32) NOT NULL, 
    	CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
    )
    
    ]
    (Background on this error at: http://sqlalche.me/e/13/f405)
    
[D 2021-07-27 10:47:25.243 JupyterHub application:653] Exiting application: jupyterhub

```
</details>

**Comment by manics** [comment] 2021-07-27 21:16
Hi! That version of Z2JH is quite old, can you reproduce the problem with the latest version?

Have you tried reproducing this with your own PoatgreSQL server? This will help identify whether the issue is specific to how Google Cloud are configuring or provisioning the managed databases.

**Comment by manics** [comment] 2021-07-27 21:31
I've just noticed you've also posted on Discourse:
https://discourse.jupyter.org/t/trouble-redeploying-jupyterhub-after-the-jupyterhub-schema-and-tables-postgres-were-accidentally-deleted-by-our-dba/10127

I'll therefore close this issue for now to avoid discussions occurring in two places.

**Closed by manics** 2021-07-27 21:32 UTC
Labels: bug
