### ISSUE TITLE
Z2JH on Raspberry PI Cluster exec format error on pre puller

### ISSUE THREAD

**Issue by JamesCarscadden** [jupyterhub/zero-to-jupyterhub-k8s#2253] opened 2021-06-16 15:00 UTC
### Bug description
I am attempting to set up the Z2JH chart on a Raspberry PI (arm64) based cluster and am encountering some problems with the pre Puller job/pods. Specifically we get an exec format error (unsurprising since that container does not appear to have an arm64 version. 

#### Expected behaviour
These containers should have arm64 versions

#### Actual behaviour
exec format error due to no arm64 version

### How to reproduce
Use base Z2JH chart (v1.0.0) on an arm64 based cluster node

### Your personal set up
Kubernetes v1.21.1 running on Raspberry PI 4 (8Gb) 4 node cluster.
Base OS is current version of Raspbian arm64 distribution
Using Helm to deploy the jupyterhub chart from https://jupyterhub.github.io/helm-chart/

This issue can be worked around by setting

```yaml
prePuller:
    hook:
      enabled: false
    continuous:
      enabled: false
```

in the helm values

**Comment by manics** [comment] 2021-06-16 17:15
I suspect the problem is that
https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/1a2ff6816303a9843e1a0e26da51e26d7bc9eff8/images/image-awaiter/Dockerfile#L13
isn't multi-arch.

**Comment by JamesCarscadden** [comment] 2021-06-16 18:43
I don't believe the image-awaiter is the actual problem in this case -- looking closer at the logs the initial problem (if I remove the values configuration mentioned in the issue), is that the 'hook-image-puller' pod fails with 'exec format error' actually on 'image-pull-singleuser' init container (which is probably related to #2145.)

If I add 
  prePuller:
    hook:
      enabled: false

to my values, then I encounter the same problem with 'continuous-image-puller' pod. And then finally if I also add the continuous->enabled->false as well then I get past this problem onto other issues. So that's my bad for not looking at this as closely as I should have. Likely this can be considered a duplicate of #2145

**Comment by JamesCarscadden** [comment] 2021-06-16 18:45
My initial bug report I made the assumption that since the values were 'prePuller' related, that the exec format error was related to the jupyterhub/k8s-pre-puller container, but that doesn't actually appear to be used anymore. Sorry.

**Comment by manics** [comment] 2021-06-17 22:53
That would explain it, the default singleuser image doesn't support ARM64. Shall we close this? There's been a fair bit of activity on https://github.com/jupyter/docker-stacks/issues/1019 and linked PRs so hopefully it won't be too long, in the meantime you can find some alternative ARM64 builds in that thread.

**Comment by JamesCarscadden** [comment] 2021-06-17 22:55
Yup close it, I'll wait for #2145

**Comment by consideRatio** [comment] 2021-07-06 17:18
Closing as duplicate of #2145

**Closed by consideRatio** 2021-07-06 17:18 UTC
Labels: bug
